name: 'macOS CMake Build'
on: push
jobs:
  build-macos:
    name: Build on macOS
    runs-on: macos-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-osx

    steps:
      - name: Hello step
        run: echo "Hello world"

      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Prints output of run-vcpkg's action.
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_DEFAULT_TRIPLET_OUT }}' "

      - name: Run CMake+vcpkg+NinjaMulti-Config (Release configuration)
        uses: lukka/run-cmake@v10
        id: runcmake
        with:
          configurePreset: 'macos-base'
          buildPreset: 'macos-release'
