name: Linux CI

on:
  push:
    branches: [ master, dev, actions ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [debug, release]
        include:
          - config: debug
            preset: linux-debug
            build_preset: linux-debug
          - config: release
            preset: linux-release
            build_preset: linux-release
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ninja-build libgl1-mesa-dev xorg-dev
        ./vendor/vcpkg/bootstrap-vcpkg.sh

    - name: Configure CMake
      run: echo cmake --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build --preset ${{ matrix.build_preset }}

