name: Linux CI

on:
  push:
    branches: [ master, dev, actions ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [debug, release]
        include:
          - config: debug
            preset: linux-debug
            build_preset: linux-debug
          - config: release
            preset: linux-release
            build_preset: linux-release
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ninja-build libgl1-mesa-dev xorg-dev
        ./vendor/vcpkg/bootstrap-vcpkg.sh

    - name: Configure CMake
      run: cmake --preset=${{ matrix.preset }}

    - name: Build
      run: cmake --build --preset=${{ matrix.build_preset }}

    - name: Test
      if: matrix.config == 'debug'
      run: ctest --preset=ci-tests-linux