name: macOS CI

on:
  push:
    branches: [ master, dev, actions ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:


jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        config: [debug, release]
        include:
          - config: debug
            preset: macos-debug
            build_preset: macos-debug
          - config: release
            preset: macos-release
            build_preset: macos-release
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        brew install cmake ninja
        ./vendor/vcpkg/bootstrap-vcpkg.sh

    - name: Configure CMake
      run: cmake --preset=${{ matrix.preset }}

    - name: Build
      run: cmake --build --preset=${{ matrix.build_preset }}

