name: Unit Tests

on:
  push:
    branches: [master, dev, actions]
  pull_request:
    branches: [master, dev]
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build libgl1-mesa-dev xorg-dev
          ./vendor/vcpkg/bootstrap-vcpkg.sh

      - name: Configure CMake
        run: cmake --preset=linux-debug

      - name: Build
        run: cmake --build --preset=linux-debug

      - name: Test
        run: ctest --preset=ci-tests-linux

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install cmake ninja
          ./vendor/vcpkg/bootstrap-vcpkg.sh

      - name: Configure CMake
        run: cmake --preset=macos-debug

      - name: Build
        run: cmake --build --preset=macos-debug

      - name: Test
        run: ctest --preset=ci-tests-macos

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install vcpkg
        run: |
          ./vendor/vcpkg/bootstrap-vcpkg.bat

      - name: Setup LLVM/Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"

      - name: Install Ninja
        run: |
            if (-not (Get-Command ninja -ErrorAction SilentlyContinue)) {
                choco install ninja -y
            }

      - name: Configure CMake
        run: cmake --preset=win-debug

      - name: Build
        run: cmake --build --preset=windows-debug

      - name: Test
        run: ctest --preset=ci-tests-windows